version: "3.9"

services:
  lseg-x86:
    profiles: ["x86"]
    image: ruiny022/lseg-trt:x86-u22.04
    container_name: lseg-trt-x86
    runtime: nvidia
    privileged: true
    network_mode: host
    devices:
      - /dev/video4:/dev/video4
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics

  lseg-jetson:
    profiles: ["jetson"]
    image: ruiny022/lseg-trt:jetson-jp62
    container_name: lseg-trt-jetson
    privileged: true
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./:/workspace
      - /tmp/argus_socket:/tmp/argus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]